---
  - name: set hostname
   hostname: name={{ hostname }}

  - name: change hostname in network files
   shell: sed -i "s/HOSTNAME=.*/HOSTNAME={{ hostname }}/g" /etc/sysconfig/network

  - name: copy /etc/hosts files to resolve domain name
  #for clients to find proxy and server
   template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644

  #- name: stop iptables
  # service: name=iptables state=stopped enabled=no

  - name: disable selinux
   selinux: state=disabled

  - name: install python devel
   #raw specially for python  only when selinux is enabled
   raw: yum install libselinux-python -y

 - name: install epel
   yum: name=epel-release

  - name: install zabbix repo
   shell: rpm -Uvh http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
