---
  - name: install mysql-server and zabbix-server
   yum: name={{ item }} state=latest
   with_items:
     - mysql-server
     - zabbix-server
     - zabbix-server-mysql
     - zabbix-web-mysql
     - mysql
     - httpd
     - httpd-devel
     - php
     - php-cli
     - php-common
     - php-devel
     - php-pear
     - php-gd
     - php-mbstring
     - php-mysql
     - php-xml
     - MySQL-python

  - name: init mysql
   shell: mysql_install_db

  - name: start mysql-server
   service: name=mysqld state=started enabled=yes

  - name: set mysql admin password
   shell: /usr/bin/mysqladmin -u root password 'ansible'

  - name: create database zabbix_master
   mysql_db: name=zabbix_master state=present encoding=utf8 login_user=root login_password='ansible'

  - name: create zabbix master database grant
   mysql_user: name=zabbix password='master' priv=zabbix_master.*:ALL state=present

  - name: import init data
   mysql_db: name=zabbix_master state=import target=/usr/share/doc/zabbix-server-mysql-{{ zabbix_server_version }}/create/{{ item }}
   with_items:
     - schema.sql
     - images.sql
     - data.sql

  - name: change php timezone
   shell: sed -e 's@;date.timezone = .*@date.timezone = Asia/Shanghai@g' /etc/php.ini

  - name: copy /etc/zabbix/zabbix_server.conf files
   template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=0644

  - name: start zabbix_server and httpd
   service: name={{ item }} state=started enabled=yes
   with_items:
     - zabbix-server
     - httpd
